version: '3.8'
services:
  chat_db:
    image: mysql:5.7
    container_name: chat_db
    restart: always
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci', #Set the data set of the database table
      ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: chat
  chat_be:
    image: node:14
    container_name: chat_be
    working_dir: /home/node/app
    command: node dist/main.js
    volumes:
      - ./server:/home/node/app
    restart: always
    ports:
      - 3305:3305
    depends_on:
      - chat_db
  chat_fe:
    image: nginx:latest
    container_name: chat_fe
    restart: always
    ports:
      - 80:80
    depends_on:
      - chat_db
      - chat_be
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
